##########################################################################################################
# Description: This script makes the account details generated by the lego tool for let's encrypt on the
# build client available to be accessed by webservers whenever they are charged with a certificate renewal
# Author: Peter Winter
# Date: 18-04-2017
##########################################################################################################
# License Agreement:
# This file is part of The Agile Deployment Toolkit.
# The Agile Deployment Toolkit is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# The Agile Deployment Toolkit is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with The Agile Deployment Toolkit.  If not, see <http://www.gnu.org/licenses/>.
#######################################################################################################
#######################################################################################################
#!/bin/sh

#if ( [ -d ${HOME}/config/credentials ] && [ -d ${HOME}/.ssh/accounts ] )
#then
#    if ( [ ! -d ${HOME}/config/ssl/accounts ] )
#    then
#        /bin/cp -r ${HOME}/.ssh/accounts ${HOME}/config/ssl
#    fi
#fi

if ( [ -d ${HOME}/.ssh/accounts ] )
then
    ${HOME}/providerscripts/datastore/configwrapper/PutToConfigDatastore.sh ${HOME}/.ssh/accounts config/ssl recursive
fi

#if ( [ -d ${HOME}/config/credentials ] && [ ! -d ${HOME}/.ssh/accounts ] )
#then
#    if ( [ ! -d ${HOME}/.ssh/accounts ] )
#    then
#        /bin/cp -r  ${HOME}/config/ssl/accounts ${HOME}/.ssh/
#    fi
#fi

${HOME}/providerscripts/datastore/configwrapper/GetFromConfigDatastore.sh config/ssl ${HOME}/.ssh/ recursive

